version: '3.8'
services:
  database:
    container_name: notion_pg
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_DB: '${PG_DATABASE}'
    ports:
      - '5432:5432'
